; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32_s3_zero

[env:esp32_s3_zero]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_upload.flash_size = 4MB
board_build.flash_size = 4MB
board_build.partitions = default.csv
lib_deps =
  esp-arduino-libs/ESP32_Button
  adafruit/Adafruit NeoPixel
  h2zero/NimBLE-Arduino@^2.4.0
  bodmer/TFT_eSPI @ ^2.5.43
	lvgl/lvgl @ 9.5.0
build_flags = 
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
  -D USER_SETUP_LOADED=1
  -D USE_HSPI_PORT=1
  -D ST7789_DRIVER=1
  -D TFT_RGB_ORDER=TFT_BGR
  -D TFT_WIDTH=76
  -D TFT_HEIGHT=284
  -D CGRAM_OFFSET=1
  -D TFT_SCLK=12
  -D TFT_MOSI=11
  -D TFT_MISO=-1
  -D TFT_RST=7
  -D TFT_DC=6
  -D TFT_CS=-1
  -D LV_CONF_SKIP=1
  -D LV_COLOR_DEPTH=16
  -D LV_USE_LOG=1
  -D LV_FONT_MONTSERRAT_24=1
  -D LV_FONT_MONTSERRAT_32=1

[env:esp32_c3_supermini]
platform = https://github.com/platformio/platform-espressif32.git
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  esp-arduino-libs/ESP32_Button
  h2zero/NimBLE-Arduino@^2.4.0
  ; adafruit/Adafruit NeoPixel

; Necessary for USB Serial/JTAG console
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1